server:
  port: 1234

spring:
  application:
    name: config-server-git
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/15012915634/config-client.git

#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:admin@localhost:1001/eureka

